config/routes.rb
Rails.application.routes.draw do

	concern :fabricable do
		post :fabricar, on: :collection
	end

	concern :expandible do
		patch ':tipo/expandir', action: :expandir, on: :collection, as: :expandir
  	patch ':tipo/cancelar', action: :cancelar, on: :collection, as: :cancelar
	end

	# resources :galaxias, only: :index # galaxia
	get 'galaxias/:numero_galaxia::numero_sistema', to: 'galaxias#index', as: :galaxias
	post 'galaxias/navegar', to: 'galaxias#navegar', as: :navegar

	# resources :defensas, only: :index, concerns: :fabricable # defensas
	resources :naves, only: [], concerns: :fabricable # naves
	get :hangar, to: 'naves#hangar'
	get :defensa, to: 'naves#defensa'

	resources :tecnologias, only: :index, concerns: :expandible # investigación
  resources :edificios, only: :index, concerns: :expandible # edificios

  resources :cuentas, only: :show # visión general

  resources :planetas, only: :update do
    post :seleccionar, on: :collection
  end

  get :recursos, to: 'planetas#recursos', as: :recursos

  root to: 'cuentas#show', id: 1

end

app/models/modulos/edificios.rb
module Modulos::Edificios

  module Planeta
    
    def edificios
      [ mina_metal, mina_cristal, mina_deuterio, planta_energia, planta_fusion, fabrica_robots, fabrica_nanobots, hangar, almacen_metal, almacen_cristal, almacen_deuterio, laboratorio, silo ]
    end

    def minas
      [ mina_metal, mina_cristal, mina_deuterio ]
    end

    def mina_metal ;        MinaMetal.new         propietario: self, nivel: nivel_mina_metal,     porcentaje_produccion: porcentaje_produccion_mina_metal     ; end
    def mina_cristal ;      MinaCristal.new       propietario: self, nivel: nivel_mina_cristal,   porcentaje_produccion: porcentaje_produccion_mina_cristal   ; end
    def mina_deuterio ;     MinaDeuterio.new      propietario: self, nivel: nivel_mina_deuterio,  porcentaje_produccion: porcentaje_produccion_mina_deuterio  ; end
    def planta_energia ;    PlantaEnergia.new     propietario: self, nivel: nivel_planta_energia, porcentaje_produccion: porcentaje_produccion_planta_energia ; end
    def planta_fusion ;     PlantaFusion.new      propietario: self, nivel: nivel_planta_fusion,  porcentaje_produccion: porcentaje_produccion_planta_fusion  ; end
    def fabrica_robots ;    FabricaRobots.new     propietario: self, nivel: nivel_fabrica_robots    ; end
    def fabrica_nanobots ;  FabricaNanobots.new   propietario: self, nivel: nivel_fabrica_nanobots  ; end
    def hangar ;            Hangar.new            propietario: self, nivel: nivel_hangar            ; end
    def almacen_metal ;     AlmacenMetal.new      propietario: self, nivel: nivel_almacen_metal     ; end
    def almacen_cristal ;   AlmacenCristal.new    propietario: self, nivel: nivel_almacen_cristal   ; end
    def almacen_deuterio ;  AlmacenDeuterio.new   propietario: self, nivel: nivel_almacen_deuterio  ; end
    def laboratorio ;       Laboratorio.new       propietario: self, nivel: nivel_laboratorio       ; end
    def silo ;              Silo.new              propietario: self, nivel: nivel_silo              ; end
  end

  module Luna
    def edificios
      [ fabrica_robots, hangar, base_lunar, sensor_phalanx, salto_cuantico ]
    end

    def fabrica_robots ;    FabricaRobots.new     propietario: self, nivel: nivel_fabrica_robots    ; end
    def hangar ;            Hangar.new            propietario: self, nivel: nivel_hangar            ; end
    def base_lunar ;        BaseLunar.new         propietario: self, nivel: nivel_base_lunar        ; end
    def sensor_phalanx ;    SensorPhalanx.new     propietario: self, nivel: nivel_sensor_phalanx    ; end
    def salto_cuantico ;    SaltoCuantico.new     propietario: self, nivel: nivel_salto_cuantico    ; end
  end

end

app/controllers/edificios_controller.rb
# Edificios Controller
class EdificiosController < ApplicationController
  before_action :set_edificio, only: %w(expandir cancelar)

  def index
    @edificios = current_planeta.edificios_disponibles
  end

  def expandir
  	@edificio.expandir! current_planeta
  	redirect_to edificios_path, notice: notice
  end

  def cancelar
    @edificio.cancelar_expansion! current_planeta
    redirect_to edificios_path, notice: notice
  end

  private

  def set_edificio
    @edificio = current_planeta.send(params[:tipo])
  end

end

app/views/edificios/_edificio.html.erb
<tr>

	<td class="l">
		<%= image_tag "edificios/#{edificio.tipo}.gif" %>
	</td>

	<td class="l">
		<%= link_to edificio.class.model_name.human, '#' %> (Nivel <%= edificio.nivel %>)<br />

		<%= t "edificios.#{edificio.tipo}.resumen" %><br />

		<b>Requiere:</b>
		<% if edificio.metal.costo > 0 %>
			Metal: <b><%= content_tag :span, number_with_delimiter(edificio.metal.costo), class: (current_planeta.puede_pagar?(edificio.metal, nil, nil, nil) ? :verde : :rojo) %></b>
		<% end %>
		<% if edificio.cristal.costo > 0 %>
			Cristal: <b><%= content_tag :span, number_with_delimiter(edificio.cristal.costo), class: (current_planeta.puede_pagar?(nil, edificio.cristal.costo, nil, nil) ? :verde : :rojo) %></b>
		<% end %>
		<% if edificio.deuterio.costo > 0 %>
			Deuterio: <b><%= content_tag :span, number_with_delimiter(edificio.deuterio.costo), class: (current_planeta.puede_pagar?(nil, nil, edificio.deuterio.costo, nil) ? :verde : :rojo) %></b>
		<% end %>
		<% if edificio.energia.costo > 0 %>
			Energía: <b><%= content_tag :span, number_with_delimiter(edificio.energia.costo), class: (current_planeta.puede_pagar?(nil, nil, nil, edificio.energia.costo) ? :verde : :rojo) %></b>
		<% end %>

		<br />

		Tiempo: <%= ChronicDuration.output edificio.duracion_expansion(current_planeta), format: :short %>

		<% if !edificio.puede_costearse?(current_planeta) %>
			<br />
			<br />
			<b>Aún faltan:</b>
			Metal: <b><%= content_tag :span, costo_faltante(edificio.metal.costo, current_planeta.recurso_metal), class: :violeta %></b>
			Cristal: <b><%= content_tag :span, costo_faltante(edificio.cristal.costo, current_planeta.recurso_cristal), class: :violeta %></b>
			Deuterio: <b><%= content_tag :span, costo_faltante(edificio.deuterio.costo, current_planeta.recurso_deuterio), class: :violeta %></b>
			Energía: <b><%= content_tag :span, costo_faltante(edificio.energia.costo, current_planeta.recurso_energia), class: :violeta %></b>
		<% end %>
	</td>

	<td class="k">
		<% if edificio.esta_expandiendose? %>
			<%= tiempo edificio %>
			<%= link_to "Cancelar", cancelar_edificios_path(tipo: edificio.tipo), method: :patch if edificio.puede_cancelar_expansion? %>
		<% elsif edificio.proceso.present? %>
			<%= content_tag :span, 'Actualizando...', class: :violeta %>
		<% elsif edificio.puede_expandirse? %>
			<%= link_to edificio.nivel.zero? ? 'Construir' : "Ampliar al nivel #{edificio.proximo_nivel}", expandir_edificios_path(tipo: edificio.tipo), method: :patch, class: :verde %>
		<% elsif !current_planeta.edificios.any?(&:esta_expandiendose?) %>
			<%= content_tag :span, edificio.nivel.zero? ? 'Construir' : "Ampliar al nivel #{edificio.proximo_nivel}", class: :rojo %>
		<% else %>
			-
		<% end %>
	</td>

</tr>

app/views/edificios/index.html.erb
<table width="569">
	<tr><td class="c" colspan="3">Edificios</td></tr>
	<%= render @edificios %>
</table>