config/routes.rb
Rails.application.routes.draw do

	concern :fabricable do
		post :fabricar, on: :collection
	end

	concern :expandible do
		patch ':tipo/expandir', action: :expandir, on: :collection, as: :expandir
  	patch ':tipo/cancelar', action: :cancelar, on: :collection, as: :cancelar
	end

	# resources :galaxias, only: :index # galaxia
	get 'galaxias/:numero_galaxia::numero_sistema', to: 'galaxias#index', as: :galaxias
	post 'galaxias/navegar', to: 'galaxias#navegar', as: :navegar

	# resources :defensas, only: :index, concerns: :fabricable # defensas
	resources :naves, only: [], concerns: :fabricable # naves
	get :hangar, to: 'naves#hangar'
	get :defensa, to: 'naves#defensa'

	resources :tecnologias, only: :index, concerns: :expandible # investigación
  resources :edificios, only: :index, concerns: :expandible # edificios

  resources :cuentas, only: :show # visión general

  resources :planetas, only: :update do
    post :seleccionar, on: :collection
  end

  get :recursos, to: 'planetas#recursos', as: :recursos

  root to: 'cuentas#show', id: 1

end

app/models/modulos/naves.rb
module Modulos::Naves

  class NaveCollection
    include ActiveModel::Model
    attr_accessor :collection

    def all
      collection
    end

    def disponible
      @disponible ||= collection.select(&:cumple_requisitos?)
    end

    def procesos
      all.map(&:procesos).flatten.sort_by(&:run_at)
    end

    def fabricando
      all.select(&:esta_fabricandose?) # { |nave| nave.proceso.present? }
    end
  end

  def naves_ataque
    @naves_ataque ||= NaveCollection.new(collection: [ carga_chica, carga_grande, cazador_ligero, cazador_pesado, crucero, colonizador, reciclador, nave_batalla, sonda_espionaje, bombardero, satelite_solar, destructor, estrella_muerte, acorazado ])
  end

  def naves_defensa
    @naves_defensa ||= NaveCollection.new(collection: [ lanzamisiles, laser_chico, laser_grande, canon_ionico, canon_gauss, canon_plasma, cupula_chica, cupula_grande, misil_intercepcion, misil_interplanetario ])
  end

  def carga_chica ;           CargaChica.new            propietario: self, cantidad: cantidad_carga_chica           ; end
  def carga_grande ;          CargaGrande.new           propietario: self, cantidad: cantidad_carga_grande          ; end
  def cazador_ligero ;        CazadorLigero.new         propietario: self, cantidad: cantidad_cazador_ligero        ; end
  def cazador_pesado ;        CazadorPesado.new         propietario: self, cantidad: cantidad_cazador_pesado        ; end
  def crucero ;               Crucero.new               propietario: self, cantidad: cantidad_crucero               ; end
  def colonizador ;           Colonizador.new           propietario: self, cantidad: cantidad_colonizador           ; end
  def reciclador ;            Reciclador.new            propietario: self, cantidad: cantidad_reciclador            ; end
  def nave_batalla ;          NaveBatalla.new           propietario: self, cantidad: cantidad_nave_batalla          ; end
  def sonda_espionaje ;       SondaEspionaje.new        propietario: self, cantidad: cantidad_sonda_espionaje       ; end
  def bombardero ;            Bombardero.new            propietario: self, cantidad: cantidad_bombardero            ; end
  def satelite_solar ;        SateliteSolar.new         propietario: self, cantidad: cantidad_satelite_solar        ; end
  def destructor ;            Destructor.new            propietario: self, cantidad: cantidad_destructor            ; end
  def estrella_muerte ;       EstrellaMuerte.new        propietario: self, cantidad: cantidad_estrella_muerte       ; end
  def acorazado ;             Acorazado.new             propietario: self, cantidad: cantidad_acorazado             ; end

  def lanzamisiles ;          Lanzamisiles.new          propietario: self, cantidad: cantidad_lanzamisiles          ; end
  def laser_chico ;           LaserChico.new            propietario: self, cantidad: cantidad_laser_chico           ; end
  def laser_grande ;          LaserGrande.new           propietario: self, cantidad: cantidad_laser_grande          ; end
  def canon_ionico ;          CanonIonico.new           propietario: self, cantidad: cantidad_canon_ionico          ; end
  def canon_gauss ;           CanonGauss.new            propietario: self, cantidad: cantidad_canon_gauss           ; end
  def canon_plasma ;          CanonPlasma.new           propietario: self, cantidad: cantidad_canon_plasma          ; end
  def cupula_chica ;          CupulaChica.new           propietario: self, cantidad: cantidad_cupula_chica          ; end
  def cupula_grande ;         CupulaGrande.new          propietario: self, cantidad: cantidad_cupula_grande         ; end
  def misil_intercepcion ;    MisilIntercepcion.new     propietario: self, cantidad: cantidad_misil_intercepcion    ; end
  def misil_interplanetario ; MisilInterplanetario.new  propietario: self, cantidad: cantidad_misil_interplanetario ; end

end

app/controllers/naves_controller.rb
# Naves Controller
class NavesController < ApplicationController

  def hangar
    @titulo = 'Hangar'
    @naves = current_planeta.naves_ataque.disponible
    @naves_construyendo = current_planeta.naves_ataque.fabricando
    @procesos = current_planeta.naves_ataque.procesos
    render :index
  end

  def defensa
    @titulo = 'Defensa'
    @naves = current_planeta.naves_defensa.disponible
    @naves_construyendo = current_planeta.naves_defensa.fabricando
    @procesos = current_planeta.naves_defensa.procesos
    render :index
  end

  def fabricar
    for nave, cantidad in params[:nave]
      @nave = current_planeta.send nave
      @nave.fabricar! cantidad
    end
    redirect_to :back, notice: notice
  end

end

app/views/naves/_nave.html.erb
<tr>

	<td class="l">
		<%= image_tag "naves/#{nave.tipo}.gif" %>
	</td>

	<td class="l">
		<%= link_to nave.class.model_name.human, '#' %>
		<% if nave.cantidad > 0 %>
			(<%= pluralize nave.cantidad, 'disponible' %>)
		<% end %>
		<br />

		<%= t "naves.#{nave.tipo}.resumen" %><br />

		<b>Requiere:</b>
		<% if nave.metal.costo > 0 %>
			Metal: <b><%= content_tag :span, number_with_delimiter(nave.metal.costo), class: (current_planeta.puede_pagar?(nave.metal, nil, nil, nil) ? :verde : :rojo) %></b>
		<% end %>
		<% if nave.cristal.costo > 0 %>
			Cristal: <b><%= content_tag :span, number_with_delimiter(nave.cristal.costo), class: (current_planeta.puede_pagar?(nil, nave.cristal.costo, nil, nil) ? :verde : :rojo) %></b>
		<% end %>
		<% if nave.deuterio.costo > 0 %>
			Deuterio: <b><%= content_tag :span, number_with_delimiter(nave.deuterio.costo), class: (current_planeta.puede_pagar?(nil, nil, nave.deuterio.costo, nil) ? :verde : :rojo) %></b>
		<% end %>
		<% if nave.energia.costo > 0 %>
			Energía: <b><%= content_tag :span, number_with_delimiter(nave.energia.costo), class: (current_planeta.puede_pagar?(nil, nil, nil, nave.energia.costo) ? :verde : :rojo) %></b>
		<% end %>

		<br />

		Tiempo: <%= ChronicDuration.output nave.duracion_expansion(current_planeta), format: :short %>

		<% if !nave.puede_costearse?(current_planeta) %>
			<br />
			<br />
			<b>Aún faltan:</b>
			Metal: <b><%= content_tag :span, costo_faltante(nave.metal.costo, current_planeta.recurso_metal), class: :violeta %></b>
			Cristal: <b><%= content_tag :span, costo_faltante(nave.cristal.costo, current_planeta.recurso_cristal), class: :violeta %></b>
			Deuterio: <b><%= content_tag :span, costo_faltante(nave.deuterio.costo, current_planeta.recurso_deuterio), class: :violeta %></b>
			Energía: <b><%= content_tag :span, costo_faltante(nave.energia.costo, current_planeta.recurso_energia), class: :violeta %></b>
		<% end %>
	</td>

	<td class="k">
		<% if current_planeta.puede_fabricar?(nave) %>
			<%= f.text_field nave.tipo, required: false, size: 10, id: nave.tipo %><br />
			<%= link_to "(Max: #{current_planeta.cantidad_maxima_fabricacion nave})", "#agregar", class: 'set-fabricacion', data: { target: "##{nave.tipo}", cantidad: current_planeta.cantidad_maxima_fabricacion(nave) } %>
		<% else %>
			-
		<% end %>
	</td>

</tr>

app/views/naves/index.html.erb
<% if @naves.empty? %>
	<p>MENSAJE</p>
<% else %>
  <%= simple_form_for :nave, url: fabricar_naves_path do |f| %>
    <table width="569">
    	<tr><td class="c" colspan="3"><%= @titulo %></td></tr>
    	<%= render @naves, f: f %>
      <tr><td class="c" colspan="3" align="center"><%= f.button :submit, 'Fabricar' %></td></tr>
    </table>
  <% end %>

	<% if @procesos.any? %>
		<br />
		Producción actual:
		<div id="bx" class="z"><%= render @procesos.first.payload_object %></div>
		<br />
		<table>
			<tbody>
				<tr>
					<th>
						<select name="auftr" size="10">
							<% @procesos.each_with_index do |proceso, i| %>
								<option><%= proceso.payload_object.cantidad_restante.next %> "<%= proceso.payload_object.fabricado.to_label %>" <%= "(En funcionamiento)" if i.zero? %></option>
							<% end %>
						</select>
					</th>
				</tr>
			</tbody>
		</table>
		<br />
	 	00h 15m 58s
	<% end %>
<% end %>