config/routes.rb
Rails.application.routes.draw do

	concern :fabricable do
		post :fabricar, on: :collection
	end

	concern :expandible do
		patch ':tipo/expandir', action: :expandir, on: :collection, as: :expandir
  	patch ':tipo/cancelar', action: :cancelar, on: :collection, as: :cancelar
	end

	# resources :galaxias, only: :index # galaxia
	get 'galaxias/:numero_galaxia::numero_sistema', to: 'galaxias#index', as: :galaxias
	post 'galaxias/navegar', to: 'galaxias#navegar', as: :navegar

	# resources :defensas, only: :index, concerns: :fabricable # defensas
	resources :naves, only: [], concerns: :fabricable # naves
	get :hangar, to: 'naves#hangar'
	get :defensa, to: 'naves#defensa'

	resources :tecnologias, only: :index, concerns: :expandible # investigación
  resources :edificios, only: :index, concerns: :expandible # edificios

  resources :cuentas, only: :show # visión general

  resources :planetas, only: :update do
    post :seleccionar, on: :collection
  end

  get :recursos, to: 'planetas#recursos', as: :recursos

  root to: 'cuentas#show', id: 1

end

app/models/modulos/tecnologias.rb
module Modulos::Tecnologias

  def tecnologias
   [ tecnologia_espionaje, tecnologia_computacion, tecnologia_militar, tecnologia_defensa, tecnologia_blindaje, tecnologia_energia, tecnologia_hiperespacio, tecnologia_combustion, tecnologia_impulso, tecnologia_propulsor_hiperespacial, tecnologia_laser, tecnologia_ionica, tecnologia_plasma, tecnologia_red_investigacion, tecnologia_graviton ]
  end

  def tecnologia_espionaje ;                   TecnologiaEspionaje.new               propietario: self, nivel: nivel_tecnologia_espionaje               ; end
  def tecnologia_computacion ;                 TecnologiaComputacion.new             propietario: self, nivel: nivel_tecnologia_computacion             ; end
  def tecnologia_militar ;                     TecnologiaMilitar.new                 propietario: self, nivel: nivel_tecnologia_militar                 ; end
  def tecnologia_defensa ;                     TecnologiaDefensa.new                 propietario: self, nivel: nivel_tecnologia_defensa                 ; end
  def tecnologia_blindaje ;                    TecnologiaBlindaje.new                propietario: self, nivel: nivel_tecnologia_blindaje                ; end
  def tecnologia_energia ;                     TecnologiaEnergia.new                 propietario: self, nivel: nivel_tecnologia_energia                 ; end
  def tecnologia_hiperespacio ;                TecnologiaHiperespacio.new            propietario: self, nivel: nivel_tecnologia_hiperespacio            ; end
  def tecnologia_combustion ;                  TecnologiaCombustion.new              propietario: self, nivel: nivel_tecnologia_combustion              ; end
  def tecnologia_impulso ;                     TecnologiaImpulso.new                 propietario: self, nivel: nivel_tecnologia_impulso                 ; end
  def tecnologia_propulsor_hiperespacial ;     TecnologiaPropulsorHiperespacial.new  propietario: self, nivel: nivel_tecnologia_propulsor_hiperespacial ; end
  def tecnologia_laser ;                       TecnologiaLaser.new                   propietario: self, nivel: nivel_tecnologia_laser                   ; end
  def tecnologia_ionica ;                      TecnologiaIonica.new                  propietario: self, nivel: nivel_tecnologia_ionica                  ; end
  def tecnologia_plasma ;                      TecnologiaPlasma.new                  propietario: self, nivel: nivel_tecnologia_plasma                  ; end
  def tecnologia_red_investigacion ;           TecnologiaRedInvestigacion.new        propietario: self, nivel: nivel_tecnologia_red_investigacion       ; end
  def tecnologia_graviton ;                    TecnologiaGraviton.new                propietario: self, nivel: nivel_tecnologia_graviton                ; end

end

app/controllers/tecnologias_controller.rb
# Tecnologías Controller
class TecnologiasController < ApplicationController
  before_action :set_tecnologia, only: %w(expandir cancelar)

  def index
    @tecnologias = current_planeta.tecnologias_disponibles
  end

  def expandir
  	@tecnologia.expandir! current_planeta
  	redirect_to tecnologias_path, notice: notice
  end

  def cancelar
    @tecnologia.cancelar_expansion! current_planeta
    redirect_to tecnologias_path, notice: notice
  end

  private

  def set_tecnologia
    @tecnologia = current_planeta.cuenta.send(params[:tipo])
  end

end

app/views/tecnologias/_tecnologia.html.erb
<tr>

	<td class="l">
		<%= image_tag "tecnologias/#{tecnologia.tipo}.gif" %>
	</td>

	<td class="l">
		<%= link_to tecnologia.class.model_name.human, '#' %> (Nivel <%= tecnologia.nivel %>)<br />

		<%= t "tecnologias.#{tecnologia.tipo}.resumen" %><br />

		<b>Requiere:</b>
		<% if tecnologia.metal.costo > 0 %>
			Metal: <b><%= content_tag :span, number_with_delimiter(tecnologia.metal.costo), class: (current_planeta.puede_pagar?(tecnologia.metal.costo, nil, nil, nil) ? :verde : :rojo) %></b>
		<% end %>
		<% if tecnologia.cristal.costo > 0 %>
			Cristal: <b><%= content_tag :span, number_with_delimiter(tecnologia.cristal.costo), class: (current_planeta.puede_pagar?(nil, tecnologia.cristal.costo, nil, nil) ? :verde : :rojo) %></b>
		<% end %>
		<% if tecnologia.deuterio.costo > 0 %>
			Deuterio: <b><%= content_tag :span, number_with_delimiter(tecnologia.deuterio.costo), class: (current_planeta.puede_pagar?(nil, nil, tecnologia.deuterio.costo, nil) ? :verde : :rojo) %></b>
		<% end %>
		<% if tecnologia.energia.costo > 0 %>
			Energía: <b><%= content_tag :span, number_with_delimiter(tecnologia.energia.costo), class: (current_planeta.puede_pagar?(nil, nil, nil, tecnologia.energia.costo) ? :verde : :rojo) %></b>
		<% end %>

		<br />

		Tiempo: <%= ChronicDuration.output tecnologia.duracion_expansion(current_planeta), format: :short %>

		<% if !tecnologia.puede_costearse?(current_planeta) %>
			<br />
			<br />
			<b>Aún faltan:</b>
			Metal: <b><%= content_tag :span, costo_faltante(tecnologia.metal.costo, current_planeta.recurso_metal), class: :violeta %></b>
			Cristal: <b><%= content_tag :span, costo_faltante(tecnologia.cristal.costo, current_planeta.recurso_cristal), class: :violeta %></b>
			Deuterio: <b><%= content_tag :span, costo_faltante(tecnologia.deuterio.costo, current_planeta.recurso_deuterio), class: :violeta %></b>
			Energía: <b><%= content_tag :span, costo_faltante(tecnologia.energia.costo, current_planeta.recurso_energia), class: :violeta %></b>
		<% end %>
	</td>

	<td class="k">
		<% if tecnologia.esta_expandiendose? %>
			<%= tiempo tecnologia %>
			<%= link_to "Cancelar", cancelar_tecnologias_path(tipo: tecnologia.tipo), method: :patch if tecnologia.puede_cancelar_expansion? %>
		<% elsif tecnologia.proceso.present? %>
			<%= content_tag :span, 'Actualizando...', class: :violeta %>
		<% elsif current_planeta.puede_investigar?(tecnologia) %>
			<%= link_to tecnologia.nivel.zero? ? 'Investigar' : "Ampliar al nivel #{tecnologia.proximo_nivel}", expandir_tecnologias_path(tipo: tecnologia.tipo), method: :patch, class: :verde %>
		<% elsif !current_cuenta.tecnologias.any?(&:esta_expandiendose?) %>
			<%= content_tag :span, tecnologia.nivel.zero? ? 'Investigar' : "Ampliar al nivel #{tecnologia.proximo_nivel}", class: :rojo %>
		<% else %>
			-
		<% end %>
	</td>
</tr>

app/views/tecnologias/index.html.erb
<% if @tecnologias.empty? %>
	<p>Para investigar primero tienes que construir el laboratorio de investigación!</p>
<% else %>
	<table width="569">
		<tr><td class="c" colspan="3">Tecnologías</td></tr>
		<%= render @tecnologias %>
	</table>

<% end %>