config/routes.rb
Rails.application.routes.draw do

	concern :fabricable do
		post :fabricar, on: :collection
	end

	concern :expandible do
		patch ':tipo/expandir', action: :expandir, on: :collection, as: :expandir
  	patch ':tipo/cancelar', action: :cancelar, on: :collection, as: :cancelar
	end

	# resources :galaxias, only: :index # galaxia
	get 'galaxias/:numero_galaxia::numero_sistema', to: 'galaxias#index', as: :galaxias
	post 'galaxias/navegar', to: 'galaxias#navegar', as: :navegar

	# resources :defensas, only: :index, concerns: :fabricable # defensas
	resources :naves, only: [], concerns: :fabricable # naves
	get :hangar, to: 'naves#hangar'
	get :defensa, to: 'naves#defensa'

	resources :tecnologias, only: :index, concerns: :expandible # investigación
  resources :edificios, only: :index, concerns: :expandible # edificios

  resources :cuentas, only: :show # visión general

  resources :planetas, only: :update do
    post :seleccionar, on: :collection
  end

  get :recursos, to: 'planetas#recursos', as: :recursos

  root to: 'cuentas#show', id: 1

end

app/controllers/application_controller.rb
# Application Controller
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_universo, :current_cuenta, :current_planeta

  rescue_from Excepciones::Nivelable::FalloExpansion, with: :mensaje_excepcion
  rescue_from Excepciones::Nivelable::FalloCancelacion, with: :mensaje_excepcion

  def current_user
  end

  def current_planeta
    session[:current_planeta_id] ||= current_cuenta.planeta_principal.id
  	@current_planeta ||= current_cuenta.planetas.find session[:current_planeta_id]
  rescue ActiveRecord::RecordNotFound => excepciont
    session[:current_planeta_id] = nil
    current_planeta
  end

  def current_cuenta
    session[:current_cuenta_id] ||= 1
    @current_cuenta ||= Cuenta.find session[:current_cuenta_id]
  end

  def current_universo
    @current_universo ||= Universo.first
  end

  private

  def mensaje_excepcion(excepcion)
    redirect_to :back, alert: excepcion.message
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	CLASES = { alert: :danger, notice: :success, info: :info }

  def bootstrap_flash
    flash.map do |key, mensaje|
      content_tag :div, mensaje, class: ["alert", "alert-block", "alert-#{CLASES[key.to_sym]}"]
    end.join.html_safe
  end

  def tiempo(elemento)
    segundos = elemento.tiempo_restante
  	content_tag :time, ChronicDuration.output(segundos, format: :short), datetime: "+#{segundos.to_i}s", data: { countdown: true } if segundos
  end

  def fecha(una_fecha, opciones = {})
    una_fecha.present? ? l(una_fecha, opciones) : "-"
  end

end

app/views/application/_header.html.erb
<div id='header_top'>
	<center>
		<table class="header">
			<tr class="header">
				<td class="header">
					<table class="header">
						<tr class="header">
							<td class="header"><%= image_tag "planetas/#{current_planeta.imagen_name}.jpg", class: :planeta %></td>
							<td class="header" align="right">
								<%= form_tag seleccionar_planetas_path, class: :seleccionar do %>
									<%= select_tag :id, options_from_collection_for_select(current_cuenta.cuerpos_celestes, :id, :to_label, current_planeta.id) %>
								<% end %>
							</td>
						</tr>
					</table>
				</td>
				<td class="header">
					<table class='header'>
						<tr class='header'>
							<td align="center" width="85" class='header'><%= image_tag 'recursos/metal.gif' %></td>
				 			<td align="center" width="85" class='header'><%= image_tag 'recursos/cristal.gif' %></td>
							<td align="center" width="85" class='header'><%= image_tag 'recursos/deuterio.gif' %></td>
							<td align="center" width="85" class='header'><%= image_tag 'recursos/energia.gif' %></td>
						</tr>

						<tr class='header'>
							<td align="center" class="header resources" width="85"><i><b>Metal</b></i></td>
							<td align="center" class="header resources" width="85"><i><b>Cristal</b></i></td>
							<td align="center" class="header resources" width="85"><i><b>Deuterio</b></i></td>
							<td align="center" class="header resources" width="85"><i><b>Energía</b></i></td>
						</tr>

						<tr class='header'>
							<td align="center" class='header' width="90"><%= number_with_delimiter current_planeta.recurso_metal %></td>
							<td align="center" class='header' width="90"><%= number_with_delimiter current_planeta.recurso_cristal %></td>
							<td align="center" class='header' width="90"><%= number_with_delimiter current_planeta.recurso_deuterio %></td>
							<td align="center" class='header <%= :rojo if current_planeta.energia_negativa? %>' width="90"><%= number_with_delimiter current_planeta.recurso_energia_disponible %>/<%= number_with_delimiter current_planeta.recurso_energia %></td>
						</tr>
					</table>
				</td>
			</tr>
		</table>
	</center>
</div>

app/views/application/_nav.html.erb
<div id='leftmenu'>

  <center>
    <div id='menu'>

    <p>
      <span class="server">OGameOnRails</span>
      <br /><span class="servername">Universo <%= current_universo.nombre %></span>
  	</p>

    <table width="110" cellspacing="0" cellpadding="0" style="text-align:center">
      <tr><td class="info-menu"><%= image_tag 'skin/info-skin.jpg' %></td></tr>

      <tr><td><%= link_to t_menu(:vision_general), current_cuenta %></td></tr>
      <tr><td><%= link_to t_menu(:edificios), edificios_path %></td></tr>
      <tr><td><%= link_to t_menu(:recursos), recursos_path %></td></tr>
      <tr><td><%= link_to t_menu(:investigacion), tecnologias_path %></td></tr>
      <tr><td><%= link_to t_menu(:hangar), hangar_path %></td></tr>
      <tr><td><%= link_to t_menu(:flota), '#', class: 'muted' %></td></tr>
      <tr><td><%= link_to t_menu(:tecnologia), '#', class: 'muted' %></td></tr>
      <tr><td><%= link_to t_menu(:galaxia), galaxias_path(numero_galaxia: current_planeta.numero_galaxia, numero_sistema: current_planeta.numero_sistema) %></td></tr>
      <tr><td><%= link_to t_menu(:defensa), defensa_path %></td></tr>

      <tr><td class="info-menu"><%= image_tag 'skin/info-help.jpg' %></td></tr>

      <tr><td><%= link_to t_menu(:alianzas), '#', class: 'muted' %></td></tr>
      <tr><td><%= link_to t_menu(:estadisticas), '#', class: 'muted' %></td></tr>
      <tr><td><%= link_to t_menu(:buscar), '#', class: 'muted' %></td></tr>

      <tr><td class="info-menu"><%= image_tag 'skin/user-menu.jpg' %></td></tr>

      <tr><td><%= link_to t_menu(:mensajes), '#', class: 'muted' %></td></tr>
      <tr><td><%= link_to t_menu(:notas), '#', class: 'muted' %></td></tr>
      <tr><td><%= link_to t_menu(:lista_de_companeros), '#', class: 'muted' %></td></tr>
      <tr><td><%= link_to t_menu(:salir), '#', class: 'muted' %></td></tr>

    </table>
  </center>

</div>